services:
  database_cpo:
    image: postgres
    container_name: database_kabum
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=kabum
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local